### ISSUE TITLE
Typo in website URL

### ISSUE THREAD

**Issue by bzg** [turbopape/postagga#7]
First of all **thanks** for this library, it looks great!

Just a typo: `http://fekr.tech` seems wrong, it should be `http://www.fekr.tech` instead.

**Comment by turbopape** [comment]
Hey Bastien,

Good call! But the site fekr.tech is correctly resolved. The problem id
that I didn't push the postagga demo :)
Still working on it, hope to have it there soon!
Cheers,
Rafik

**Comment by turbopape** [comment]
But for a weird reason, it wouldn't redirect to the landing form Github.
Any how, I fixed it as per your recommendation, thank you !

**Comment by bzg** [comment]
Thanks for the quick fix! Looking forward testing the library soon.

**Comment by turbopape** [comment]
You're welcome!
